### ISSUE TITLE
Handle unknown errors

### ISSUE THREAD

**Issue by jmks** [jmks/kconnectex#14]
Handle unknown errors in a nicer way, so these do not get spit out:

```
Error with request:
** (FunctionClauseError) no function clause matching in Kconnectex.CLI.error_description/1

    The following arguments were given to Kconnectex.CLI.error_description/1:

        # 1
        :closed

    (kconnectex 0.3.0) lib/kconnectex/cli.ex:278: Kconnectex.CLI.error_description/1
    (kconnectex 0.3.0) lib/kconnectex/cli.ex:275: Kconnectex.CLI.display/1
    (elixir 1.12.2) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by jmks** [comment]
```
Error with request:
** (FunctionClauseError) no function clause matching in Kconnectex.CLI.error_description/1

    The following arguments were given to Kconnectex.CLI.error_description/1:

        # 1
        :nxdomain
```
